### ISSUE TITLE
core/style/layout.scss has bad charcter

### ISSUE THREAD

**Issue by Son-Lam** [justindujardin/ng2-material#122] opened 2016-03-22 19:22 UTC
I found a bad character in the file at line 170:

// IE mediaQuery hack for 8,9,10 to set the flex-basis properly for 'flex' values
  // Details:
  // Do not use unitless flex-basis values in the flex shorthand because IE 10-11 will error.
  // Also use 0% instead of 0px since minifiers will often convert 0px to 0 (which is unitless and will have the same problem).
  // Safari, however, fails with flex-basis : 0% and requires flex-basis : 0px
  @media screen\0
  {
    [#{$flexName}] {
      flex: 1 1 0%;
    }
  }

**Comment by ruid0** [comment] 2016-03-24 07:05
Same issue

**Comment by alex-alexandrescu** [comment] 2016-03-24 14:31
Guys are you by any chance compiling with gulp?

**Comment by jaroslavrehorka** [comment] 2016-03-27 10:50
there is an extra space between **screen** and **\0** (caused by autoformating) which should not be there it is already fixed in master

maybe @justindujardin can release new version with this fix? please

**Comment by justindujardin** [comment] 2016-03-27 15:58
Sorry this took a while, 0.2.13 is published to NPM now.

**Closed by justindujardin** 2016-03-27 15:58 UTC

**Comment by ruid0** [comment] 2016-03-28 01:03
@justindujardin Thx :)
