### ISSUE TITLE
Sidenav doesn't behave (well...work) when using ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by aberenyi** [justindujardin/ng2-material#63] opened 2016-02-18 20:41 UTC
Hi - is there anything that one could/should do to get around this?

Cheers

**Comment by spencersmb** [comment] 2016-02-20 07:17
My install seems to be missing SidenavService as well....having trouble following the sidenav example.

**Comment by justindujardin** [comment] 2016-02-20 23:50
@spencersmb @aberenyi please provide a plunkr example or code sample to reproduce this error.

**Comment by spencersmb** [comment] 2016-02-21 05:35
@justindujardin Hey man - here is a link to my git repository - I think it would be most helpful to look at it and let me know whats going on: [Repo](https://github.com/spencersmb/ng2-material-intro.git)
In this repo I have 3 components - one of which is the sidenav that I was trying to get to work, but I couldn't reproduce what you have on your demo site for the sidenav in a basic form. I couldn't figure out how to import the sidenav service. Anyways hope this helps - anything else I can help with let me know too. Another note - when using the most recent beta version of NG2 - and your version of Material - I got duplicate ts file errors - I think others have reported this though already.
Cheers,
S

**Comment by djarnop** [comment] 2016-02-21 11:31
@justindujardin do I need to compile it someway ?

If I upgrade (well update) 2 CSS files disappear

  <link rel="stylesheet" href="/ng2-material/dist/ng2-material.css">
  <link rel="stylesheet" href="/ng2-material/dist/font.css">.

**Comment by djarnop** [comment] 2016-02-21 11:31
"stylesheet" href="/ng2-material/dist/ng2-material.css"
"stylesheet" href="/ng2-material/dist/font.css"

**Comment by aberenyi** [comment] 2016-02-21 19:06
@justindujardin sure thing. Please have a look at this [commit](https://github.com/aberenyi/ng2-material/commit/1e4059b88bd288bd847593d5107f3df38bc1f77f) in my fork.

**Comment by technoSpino** [comment] 2016-02-22 16:09
Also getting this issue. I am having trouble making an up-to-date plunkr. I just have a webpack project, beta.7 with "ng2-material": "^0.2.5" nothing else.

**Comment by justindujardin** [comment] 2016-05-22 22:38
The sidenav component has been replaced with the [Material2 sidenav](https://github.com/angular/material2/tree/master/src/components/sidenav) component as of version `0.4.1`.  Closing this issue.

**Closed by justindujardin** 2016-05-22 22:38 UTC
Labels: needs-more-info
