### ISSUE TITLE
ionic2

### ISSUE THREAD

**Issue by uiktiomasfeliz** [justindujardin/ng2-material#16] opened 2016-01-10 22:04 UTC
Fails the wave effect on button click, and i can't implement the css from local, need to use CDN.
It can be my fault?

**Comment by justindujardin** [comment] 2016-01-12 02:17
I don't understand what problem you are having. Maybe there is a language barrier. Can you provide an example of what is not working? Thanks.

**Comment by uiktiomasfeliz** [comment] 2016-01-13 18:58
i have app.ts

```javascript
import {App, Platform, Config} from 'ionic-framework/ionic';
import {MATERIAL_DIRECTIVES, MATERIAL_PROVIDERS} from 'ng2-material/all';

import {HomePage} from './pages/home/home';

@App({
  template: `
    <ion-nav [root]="root"></ion-nav>
  `,
  directives: [MATERIAL_DIRECTIVES],
  // Check out the config API docs for more info
  // http://ionicframework.com/docs/v2/api/config/Config/
  config: {}

})
export class MyApp {
  constructor(platform: Platform) {
    this.platform = platform;
    this.initializeApp();
    this.root = HomePage;
  }

  initializeApp() {
    this.platform.ready().then(() => {
      console.log('Platform ready');
    });
  }
}
```

and i tried to implement in the scss

$md-font-url: 'node_modules/ng2-material/dist/';
@import "node_modules/ng2-material/dist/font";
@import "node_modules/ng2-material/all";

**Comment by justindujardin** [comment] 2016-01-17 00:02
@uiktiomasfeliz I think you're having the same troubles as people in #17 

The issue is that the example on the main page was incorrect.  In the example it says:
```scss
@import "node_modules/ng2-material/all";
```
but it should be:

```scss
@import "node_modules/ng2-material/source/all";
```

**Comment by justindujardin** [comment] 2016-01-17 00:54
This should be fixed in the latest website deploy.  Please reopen this issue if you're still having problems.

**Closed by justindujardin** 2016-01-17 00:54 UTC

**Comment by uiktiomasfeliz** [comment] 2016-01-18 23:25
tried to use -> import "node_modules/ng2-material/source/all";
now i got this error:
./~/ng2-material/source/all.ts
Module parse failed: C:\Users\mou\Desktop\ionic\testIonic2\vigilanty\node_modules\ng2-material\source\all.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import {CONST_EXPR, Type} from 'angular2/src/facade/lang';
|
| import {MdAnchor, MdButton} from './components/button/button';
 @ ./app/app.ts 12:12-46 (CLI v2.0.0-beta.17)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.49
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS:
Node Version: v4.2.1
