### ISSUE TITLE
 MdDataTable tr uses a tr tag selector

### ISSUE THREAD

**Issue by wallace41290** [justindujardin/ng2-material#134] opened 2016-03-28 13:32 UTC
This is causing a name-space issue when trying to use a <tr> element. It will result in an EXCEPTION: No provider for MdDataTable! (MdDataTableTr -> MdDataTable). I suggest changing the selector to avoid conflicts in data_table_tr.ts

**Comment by szechyjs** [comment] 2016-03-28 15:58
Duplicate of #133

**Closed** 2016-03-28 19:02 UTC

**Comment by justindujardin** [comment] 2016-03-29 15:29
Fixed with 0.3.4, and deployed to npm.
