### ISSUE TITLE
Installing this module in a project with Angular 2 beta 1 breaks Typescript compling

### ISSUE THREAD

**Issue by LuxDie** [justindujardin/ng2-material#20] opened 2016-01-16 00:39 UTC
Hi. Given that `ng2-material` requires Angular 2 beta 0, it installs this version of Angular2 inside its `node_modules` directory. When you run the Typescript compiler, it finds about 1500 "duplicate identifier" errors, which are already loaded from the beta 1 version of Angular 2.

**Comment by justindujardin** [comment] 2016-01-17 00:53
Sorry but beta 1 currently [breaks the test suite on Internet Explorer](https://travis-ci.org/justindujardin/ng2-material/builds/102865559) browsers.

I can't update the project until I can find a suitable workaround. I'll leave this issue open until the issue is resolved.

**Comment by justindujardin** [comment] 2016-01-17 22:51
I spent a few hours looking at this and can't figure out why the build is failing.  If I run the sauce labs build locally it passes every time.  It only fails on Travis. I'll probably look at this again after beta2 is released.

**Comment by hpinsley** [comment] 2016-01-18 22:20
Thanks for looking at this Justin.

**Comment by justindujardin** [comment] 2016-01-23 20:52
There's some chatter and an issue about the errors in https://github.com/angular/angular/issues/6501

I'll look into a suggested workaround today.

**Comment by justindujardin** [comment] 2016-01-25 02:04
I looked in to the suggested workaround and it did not help.  It looks like beta.1 generates invalid javascript for for IE when JITting views.

The good news is that the issue is labeled `P1: urgent`, so I am hopeful it will be fixed in Beta.2

**Comment by LuxDie** [comment] 2016-01-25 02:28
@justindujardin Cool, thanks for following this.

**Comment by justindujardin** [comment] 2016-02-08 00:52
I published version 0.2.2 today that supports the latest Beta.3 build.  Please try it out and close this issue if your problems are resolved.

**Comment by wallace41290** [comment] 2016-02-09 17:47
Great work btw on the project in general. However, today I am seeing similar issues. I updated to ng2-material .2.2 and updated my package.json to use beta.3, its spitting out 777 Duplicate identifier errors. Not sure if someone else has found the trick that I am missing?

**Closed** 2016-02-21 00:56 UTC
