### ISSUE TITLE
[webpack] - Import errors

### ISSUE THREAD

**Issue by qdouble** [justindujardin/ng2-material#17] opened 2016-01-11 03:35 UTC
Hey, I'm getting some errors when trying to incorporate it with webpack build. One error is from this and everyone else with similar formatting of the \0

```
@media screen\0 and (min-width: 600px) {
  [flex-gt-xs] {
    -webkit-box-flex: 1;
    -webkit-flex: 1 1 0%;
        -ms-flex: 1 1 0%;
            flex: 1 1 0%; } }
```
this is the error message:

```
ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader!./src/style/app.scss
Module build failed: 
@media screen\0 and (max-width: 599px) {
      ^
      Invalid CSS after "...ia screen\\0 and": expected "{", was "-width: 599px) ..."
      in /Users/qdouble/Sites/offersystem/app/admin-api/node_modules/ng2-material/all.css (line 1941, column 8)

```

**Comment by shawnrmoss** [comment] 2016-01-11 15:57
I get this same error with webpack.

**Comment by justindujardin** [comment] 2016-01-12 02:11
I am not really familiar with webpack. If someone provides an example project, with basic build instructions, I can take a look at it this weekend. Feel free to open a PR if you have a fix.

**Comment by qdouble** [comment] 2016-01-12 04:27
Webpack is what most people are using to bundle their Angular 2 projects projects right now as it isn't so easy to do with SystemJS right now... this is the seed project I'm using, it's not to bloated: https://github.com/ocombe/ng2-webpack

**Comment by Egidius** [comment] 2016-01-12 21:34
I got the same problem with gulp:

[22:30:40] Starting 'serve.dev'...
[22:30:40] Finished 'serve.dev' after 20 ms
Error in plugin 'sass'
Message:
    node_modules/ng2-material/all.css
  1941:8  Invalid CSS after "...ia screen\\0 and": expected "{", was "-width: 599px) ..."

**Comment by webnugget** [comment] 2016-01-13 14:12
```@import "node_modules/ng2-material/source/all.scss";```
worked for me

**Comment by technoSpino** [comment] 2016-01-13 16:22
@webnugget this worked for me as well

**Comment by justindujardin** [comment] 2016-01-16 20:13
I think I understand at least part of the problem here: people are `@import`ing the `all.css` file in the root of the package instead of `source/all.scss`. 

To work around this, you can use the scss files as suggested by @webnugget.

To address this further, I will suggest the following
 - [ ] Update package to include root-level scss file.
 - [ ] Investigate the correctness of the `screen\0` usage from angular/material styles.

@qdouble Can you confirm if this will resolve your issue as well?

**Comment by qdouble** [comment] 2016-01-16 20:37
@justindujardin hey, just tested it...it works now thanks.

As a side question, is an 250kb bundled normal for using material?

**Comment by justindujardin** [comment] 2016-01-16 21:08
@qdouble great to hear!

I looked into the `media\0` and it's valid markup that creates a media query that conditionally applies to specific browser versions.  See more about it here: http://keithclark.co.uk/articles/moving-ie-specific-css-into-media-blocks/media-tests/

I'll add a root-level scss file and then close this issue when it's published.

Thanks for reporting it!

**Comment by justindujardin** [comment] 2016-01-17 00:06
So it turns out that the problem is the example site.  I goofed and referenced the bad `@import` path in the getting started example.

**Closed** 2016-01-17 00:05 UTC
