### ISSUE TITLE
NPM install error (node 5.6.0 && NPM 3.6.0)

### ISSUE THREAD

**Issue by djarnop** [justindujardin/ng2-material#64] opened 2016-02-18 21:54 UTC
`node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "ng2-material"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! zone.js@0.5.11 postinstall: `tsd install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zone.js@0.5.11 postinstall script 'tsd install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zone.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsd install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zone.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zone.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Desktop\cryptobet2\npm-debug.log

C:\Users\Administrator\Desktop\cryptobet2>npm install --save zone
npm WARN saveError Unexpected end of input
C:\Users\Administrator\Desktop\cryptobet2
+-- zone@0.3.4
| `-- sl-blip@1.0.0
`-- UNMET PEER DEPENDENCY zone.js@0.5.11

npm WARN Failed to parse json
npm WARN No data, empty input at 1:1
npm WARN
npm WARN ^
npm WARN File: C:\Users\Administrator\Desktop\cryptobet2\package.json
npm WARN angular2@2.0.0-beta.3 requires a peer of zone.js@0.5.11 but none was in
stalled.
npm WARN cryptobet2 No description
npm WARN cryptobet2 No repository field.
npm WARN cryptobet2 No README data
npm WARN cryptobet2 No license field.
`

Installing it seperaty seems to work though.

**Comment by jycouet** [comment] 2016-02-19 15:41
Hi @djarnop you said:

> Installing it seperaty seems to work though.

Can you explain me? I have the same error and I can't get rid of it!
Thank you

**Comment by sylvaindumont** [comment] 2016-02-19 15:50
zone.js automatically launch tsd install, if you haven't tsd, the install fail
```
npm install -g tsd
```
wil fix your problem.

The separate install work because it's not the same package:
zone.js@0.5.11 fail
zone@0.3.4 work

The problem is fixed in zone.js v0.5.14, i will submit a pull request to update zone.js

**Comment by jycouet** [comment] 2016-02-19 17:04
Thx, it works well :)

**Closed** 2016-02-21 00:10 UTC
