### ISSUE TITLE
Add support for Angular2 RC1

### ISSUE THREAD

**Issue by justindujardin** [justindujardin/ng2-material#207] opened 2016-05-01 16:11 UTC
There have recently been breaking changes in the Angular2 code base related to content projection and the DynamicComponentLoader class which powers the MdDialog component.  

Beta 17 does not include a content projection fix, so ng2-material is locked to Beta 14 until a suitably fixed version is available.

Notes for updating:
 - beta17 branch includes most of the changes for testing and dcl
 - comments on usage of ViewContainerRef http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468
 - there is a pending fix for the content projection issues that will be in beta 18 https://github.com/angular/angular/commit/0f774df81150524c399161272a6cd51d0d54aa7e
 - Deprecation of DCL https://github.com/angular/angular/commit/5297c9d9ccc6f8831d1656915e3d78e767022517

- [x] Update angular2 package to rc0
- [x] Update tests to use `async(inject(...))` instead of deprecated `asyncInject(...)`
- [x] Update DCL usages to pass `ViewContainerRef` instead of location string.
- [x] Update MdDialog to use one of:  `Portal` or `Overlay` or `NgTemplateOutlet` 
- [x] Update `*ngFor="#item of items"` to new `*ngFor="let item of items"` syntax
- [x] Replace broken components with material2 components
- [x] Update demos
- [x] Clean up build automation
- [x] Build webpack/browserify compatible commonjs npm package
- [x] Fix travis build
- [x] Fix ink animations

**Comment by Maks3w** [comment] 2016-05-01 17:03
Why beta14? For me MdDialog works with beta15

**Comment by Drol** [comment] 2016-05-03 10:12
NG2 RC0 is released now. Any ETA on making it compatible?

**Comment by balajijana** [comment] 2016-05-03 13:35
Hi Justin,

I have used ng2-material 0.3.7 and angular-2.0.0-beta.17.

I am try to iterate the menu items and get the data in the ngFor but i am not able to get the values. See the below code:

md-list-item.md-whiteframe-z2.md-margin.white-color(md-ink , *ngFor ="let item of menuItems; let index = index",[ngClass]="{'disabled':item.disable,'active pullright': navClass(item.link)}", (click)="activeTab(item)",style="width:100%")

I am not able to get the items in the ngFor if i use md-list-item. Please let me know what is wrong in the below statement

**Comment by dotansimha** [comment] 2016-05-06 08:53
+1 for RC support!

**Comment by justindujardin** [comment] 2016-05-06 14:30
This weekend ETA

**Comment by justindujardin** [comment] 2016-05-09 01:50
I made some great progress this weekend, but the RC has left the components pretty badly beaten up. 

As a result I decided to pull forward some work on deprecating some existing components in favor of material2 ones. This also includes moving the example app to be based on angular-cli.

I did not get to finish this work such that's it's shippable now, but I did push a branch, and there's a (somewhat broken) deployed site that you can look at here: https://justindujardin.github.io/ng2-material/o/rc0-material2/index

**New ETA** Weekend of May 14th.

**Comment by axal90** [comment] 2016-05-09 06:24
@justindujardin any way to sytay in touch? so I can help out without working on the same things?

**Comment by mailiam** [comment] 2016-05-10 01:18
Nice! I was working on this only to realize I'm late. 👍

**Comment by vasslehel** [comment] 2016-05-10 14:12
It will be compatible with RC1 too?

**Comment by justindujardin** [comment] 2016-05-10 14:16
Who knows, maybe RC2 by this weekend? :trollface:  (yes, the latest RC will be supported)

@axal90 I sent you a note on gitter.

**Comment by RicardoVaranda** [comment] 2016-05-11 11:44
@justindujardin Are fabs going to be added anytime soon? Not trying to rush just genuinely curious.

**Comment by Maks3w** [comment] 2016-05-11 15:08
FAB can be do with material2 md-fab https://github.com/angular/material2/tree/master/src/components/button

**Comment by RicardoVaranda** [comment] 2016-05-12 10:26
I know mate I meant the full implementation of it including the speed dial:

https://material.angularjs.org/latest/demo/fabSpeedDial

**Comment by ollwenjones** [comment] 2016-05-12 13:09
@RicardoVaranda seems like a strange side-track of this issue, which is about RC1/2 support. I'm sure that as soon as someone in the community using this library needs it and has time to contribute it, it'll be there. Maybe you could open an issue for the speed-dial FAB.

**Comment by RicardoVaranda** [comment] 2016-05-12 15:10
I know was just wondering since Justin did mentioned above that he was moving forward into other components was wondering if this was one of them

> As a result I decided to pull forward some work on deprecating some existing components in favor of material2 ones.

**Comment by kuncevic** [comment] 2016-05-14 13:34
Any progress/estimations on this one? :trollface:

**Comment by justindujardin** [comment] 2016-05-15 16:34
I'm working on finishing up the changes for this today.

**IMPORTANT**: this includes the deprecation of some existing components entirely, and sacrifices some functionality to become aligned with the official material2 project. Apologies in advance for the inconvenience.

 - Theming overrides will no longer work.  This is because the material2 components that we're putting in place of ng2-material ones do not have theming support yet.  For now the project has locked its colors to the material2 theme defaults.
 - Some of the advanced demos like FormBuilder inputs and md-messages validation errors are removed. I'm still trying to figure out the best way to show examples of material2 components in the long term.

**Comment by justindujardin** [comment] 2016-05-15 21:40
I made more progress today, but unfortunately it's still not complete. I guess the rest of the work will need to happen next weekend. The good news is that I was able to publish a package `ng2-material@beta` on NPM for people that want to get started now.

The big blocker today is that the Travis CI build is failing because material2 packages have a dependency on beta.17 build of angular2. Once the material2 team releases a new package this should be resolved.

**Example Site**
Poke around with the deployed site as it stands: https://justindujardin.github.io/ng2-material/dev/

**Beta Package**
Install the package and brave the breaking changes.
```
npm install --save ng2-material@beta
```

Sorry for the delay, but there are only so many hours in the day.  :wave:

**Comment by zigzag95** [comment] 2016-05-16 04:44
Great job @justindujardin. J'attends ça depuis 2 semaines pour pouvoir avancer sur ls-menu.
Kr

**Comment by DennisSmolek** [comment] 2016-05-18 02:35
Hey Justin, 

I know it's a super pain to get things moved into RC.1 but I wanted to ask how you got it working for you...

I'm using the @beta release and having some issues... 

I noticed you switched to importing from `'ng2-material'` instead of from `ng2-material/all`

I can't for the life of me get that to pull the providers or directives. 

I'm using the angular-seed which I think you are using too, but in dev it doesnt build the vendor folder, in my build it isnt pulling the index.js file and I'm not sure what I'm doing wrong...

Any advice?

**Comment by tao-guo** [comment] 2016-05-18 18:33
@justindujardin Thanks your great job! 
However I tried ng2-material@beta, it seems not working with universal? (compiling is OK)
```
../node_modules/ng2-material/components/switch/switch.js:75
        __metadata('design:paramtypes', [KeyboardEvent]), 
                                         ^

ReferenceError: KeyboardEvent is not defined
``` 
I noticed that you also have a `universal-example` branch, is it working with ng2-material@beta?

**Comment by DennisSmolek** [comment] 2016-05-18 22:36
Ok not sure what I did but today the `import {MATERIAL_DIRECTIVES} from 'ng2-material';` is working as expected..

**Comment by DennisSmolek** [comment] 2016-05-18 23:14
For those using the Angular2 Seed they made some changes that if you didnt specify the path it would try to load the package.json which didnt exist. 

You have to modify the seed.config and comment out the lines for packageConfigPaths but leave the @angular one. 

What got me there: https://groups.google.com/forum/#!topic/angular-material2/7mBDJ6Mc9Lo

**Comment by ieltxu13** [comment] 2016-05-19 20:38
@DennisSmolek hi, can you show me your seed.config? i cannot get it to work!

**Comment by DennisSmolek** [comment] 2016-05-19 21:08
@ieltxu13 to be honest I've been struggling with the RC1 release as well so my solution may not be perfect but heres what I did:
Around 289:
``` javascript
  protected SYSTEM_CONFIG_DEV: any = {
    defaultJSExtensions: true,
    
    packageConfigPaths: [
    //  `${this.APP_BASE}node_modules/*/package.json`,
    //  `${this.APP_BASE}node_modules/**/package.json`,
      `${this.APP_BASE}node_modules/@angular/*/package.json`
    ],

    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      'rxjs/*': `${this.APP_BASE}rxjs/*`,
      'app/*': `/app/*`,
      '*': `${this.APP_BASE}node_modules/*`
    },
    packages: {
      rxjs: { defaultExtension: false }
    }
  };
```

This KINDA works.. The issue is now the default map of `import {MATERIAL_DIRECTIVES} from 'ng2-material';` doesn't know what to look for so it freaks out...
to get ng2-material directives I had to use `'ng2-material/index'` and with @angular-material I had to specify twice.. so `import {MdToolbar} from '@angular2-material/toolbar/toolbar';`

Another thing is Justin stripped a ton of things that my older version of ng2 had in it for the official releases (like MdCard) so if your app used those and trys to call for them it will fail..

Its not perfect at all but if you need to get working I hope I helped!

**Comment by ieltxu13** [comment] 2016-05-20 21:08
@DennisSmolek with some workarrounds it KINDA worked for me also.. Thanks!
I notice that layout (row, column) isn't working in that wranch.. is that feature going to be sacrified also @justindujardin ?

**Comment by robwafle** [comment] 2016-05-20 22:34
Hi Guys:  I've been working over the last two days from a fork I created from this repository..  I published a fork on github where I've been working.. I don't need the dialog component yet I removed it from my branch for now.   I'm wondering if anyone else might be in the same boat.  Perhaps this will help someone?  There were a few include paths I made changes to for ng2-material within examples.   I was just using tsc to start then I noticed the gruntfile.  I looked at the rc0-material2 release but so many of the angular references are not yet updated.  Perhaps some of my code could be merged and help get this module upgraded to rc1 ?

https://github.com/robwafle/ng2-material/tree/feature/upgrade-to-angular2-rc1

**Comment by Gregcop1** [comment] 2016-05-20 23:20
Hi @robwafle. Maybe you can send us a PR or more (to keep it readable) with your work to help @justindujardin in his revamp

**Comment by DennisSmolek** [comment] 2016-05-20 23:53
@ieltxu13 Here's an updated snippet:
``` javascript
      packageConfigPaths: [
      `${this.APP_BASE}node_modules/*/package.json`,
      `${this.APP_BASE}node_modules/**/package.json`,
      `${this.APP_BASE}node_modules/@angular/*/package.json`,
      `${this.APP_BASE}node_modules/@angular2-material/*/package.json`,
      `${this.APP_BASE}node_modules/ng2-material/package.json`
    ],
```

This lets me use the `'ng2-material'` and `'@angular-material/card'` as given in the examples. I haven't tried a build yet but if you scroll down you can see where you can add those packages.. 

@robwafle I agree with @Gregcop1 about doing it as a PR instead of a full fork. The version @justindujardin  mentioned is what I started with too and wasn't too hard to switch over. One thing is as he mentioned he's slashed a lot of old stuff so people will have to immediately switch to the standard m2 versions. 

Otherwise I assume he'll knockout an update over the weekend...

**Comment by robwafle** [comment] 2016-05-21 15:12
Thanks @DennisSmolek and @Gregcop1.. As my code is currently incomplete, I didn't want to submit a pull request.  The changes were in nearly every file..  From angular2/core to @angular/core ... for example.. Is the RC code only available from the npm package mentioned above?  

npm install --save ng2-material@beta 

I was looking for a github branch to work from!  Didn't think to look for a package!  I thought those came later :)

**Comment by justindujardin** [comment] 2016-05-22 22:07
Thanks for being patient, I've finally landed `0.4.1` npm package version that:

 - Supports angular2 RC1.
 - Support Webpack and Browserify module bundlers.
 - Support source map resolution while debugging in browser.
 - Uses Material2 core for components.
 - Replaces toolbar, sidenav, input, checkbox, radio, progress-circle, and progress-linear with official Material2 component implementations.
 - Component API documentation `my-component/readme.md` is rendered into example pages.
 - Angular CLI can generate new components for the example site (see `modules/site/readme.md`)

There are some breaking changes:

 - Custom theming is busted.  Because we use Material2 under the covers, we need to wait for them to support theming before we can offer it. As it stands you could certainly do a custom build if you wanted to have your own theme colors, but it's probably out of the reach of casual users.
 - The new MdDialog component (which uses the awesome Overlay/Portal system from material2) lacks tests and a backdrop overlay.
 - MdSidenav was removed in favor of the Material2 sidenav, which is much nicer. This means that your sidenav usages will need to change. Refer to the sidenav example for updated usage, or the material2 readme page.
 - Scrolling content on iOS  sidenav appears to have poor scroll performance in iOS safari browser.

I'm sure there are at least a few busted things that I did not list here.

**Closed** 2016-05-22 22:07 UTC

**Comment by Gregcop1** [comment] 2016-05-22 22:18
Awesome work @justindujardin 
I'll update current PR to fit this before review

**Comment by robwafle** [comment] 2016-05-23 13:18
Ditto.  Awesome work @justindujardin.  Giving these components a shot now.

**Comment by ojacquemart** [comment] 2016-05-24 10:49
Thanks, great work! :+1:
