### ISSUE TITLE
md-sidenav blocks overflow in body when its open

### ISSUE THREAD

**Issue by mwiesmueller** [justindujardin/ng2-material#156] opened 2016-04-07 13:11 UTC
When md-sidenav its open, ng2 material set in body-tag the style "overflow: hidden". This means that the user then no longer can scroll when the sidenav it's open.

Is it wanted like that? How to handle this without big manipulation? :-)

Thanks in advance

**Comment by axal90** [comment] 2016-04-28 19:34
I would say this is intended behavior, as scrolling with the sidenav open should scroll the sidenav not the body.

**Comment by kuncevic** [comment] 2016-05-12 09:16
I remember long ago bootstrap has similar issue when using dialog popup and that it was being fix.

It is just really annoying behavior when scroll just indecently diapered. I think it should just gets disabled but not completely dissipated which is looking wired from client point of view.

**Comment by justindujardin** [comment] 2016-05-22 22:32
The sidenav component has been replaced with the [Material2 sidenav](https://github.com/angular/material2/tree/master/src/components/sidenav) component as of version `0.4.1`.  Closing this issue.

**Closed by justindujardin** 2016-05-22 22:32 UTC
