### ISSUE TITLE
Cursor on md-input jumps to the end after every edit.

### ISSUE THREAD

**Issue by danielrasmuson** [justindujardin/ng2-material#105] opened 2016-03-13 01:34 UTC
Steps to Reproduce
1. Go to this link, https://justindujardin.github.io/ng2-material/#/components/input
2. Enter "Jumps to the end of the line" in title field
3. Remove the word "end" notice the cursor is at the end of the line.

**Comment by sylvaindumont** [comment] 2016-03-13 08:45
Seems related to #103

**Comment by Devidian** [comment] 2016-03-31 14:54
Same on my side, happening in all Browsers that use webkit (Chrome, Opera, Maxthon tested).
Firefox / Edge have no problems with that.

**Comment by yurykozyrev** [comment] 2016-05-03 08:40
Any updates on this topic?

**Comment by JanStureNielsen** [comment] 2016-05-03 10:36
+1 -- still reproducible with 0.3.7 on the Title input field when you place cursor at the front of 'Developer', cursor jumps to end after each keystroke in Chrome on Android and Linux.

**Comment by justindujardin** [comment] 2016-05-22 22:54
The input component has been replaced with the [Material2 input](https://github.com/angular/material2/tree/master/src/components/input) component as of version `0.4.1`.  Closing this issue.

**Closed by justindujardin** 2016-05-22 22:54 UTC
Labels: bug, help wanted

**Comment by vladimir-ivanov** [comment] 2016-06-15 10:42
thanks

**Comment by benirule** [comment] 2016-07-13 19:20
While I find this to be working for md-input[type="text"] it appears to be still failing for md-input[type="number"]

**Comment by benirule** [comment] 2016-07-13 21:25
I believe it's because this line is only executed for numbers https://github.com/angular/material2/blob/master/src/components/input/input.ts#L181

**Comment by benirule** [comment] 2016-07-13 21:46
I'm guessing it's the fact that value for number fields get run through parseFloat https://github.com/angular/material2/blob/master/src/components/input/input.ts#L266
and then set as the value here https://github.com/angular/material2/blob/master/src/components/input/input.ts#L181

**Comment by Gregcop1** [comment] 2016-07-14 07:17
Hi. Have you report it as an issue to the official project?

**Comment by benirule** [comment] 2016-07-14 11:55
@Gregcop1 What's the url for that?

**Comment by Gregcop1** [comment] 2016-07-14 11:59
https://github.com/angular/material2/issues
