### ISSUE TITLE
Angular CLI Build Fail

### ISSUE THREAD

**Issue by ruid0** [justindujardin/ng2-material#255] opened 2016-06-08 12:36 UTC
I'm trying to use angular2-material with ng2-material, but I have this error when trying do build

this is my angular-cli-build.js

```javascript
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      '@angular2-material/**/*',
      'ng2-material/**/*'
    ]
  });
};
```
```javascript
Error on fetch for vendor/@angular2-material/core/overlay/overlay.js at file:///tmp/bundle_plugin-input_base_path-qsoMeMzi.tmp/0/vendor/@angular2-material/core/overlay/overlay.js
	Loading vendor/ng2-material/index.js
	Loading main.js
	Error: ENOENT: no such file or directory, open '/tmp/bundle_plugin-input_base_path-qsoMeMzi.tmp/0/vendor/@angular2-material/core/overlay/usr/local/google/home/jelbourn/material2/tmp/broccoli_type_script_compiler-input_base_path-OxHzApZr.tmp/0/core/overlay/overlay.js.map'
    at Error (native)```

**Comment by justindujardin** [comment] 2016-06-11 19:18
I suspect the problem is with your `system-config.ts` file, because ng2-material's package does not import material2 with a specific path.  Your build setup is resolving to the wrong file in some way.

Look at the examples site for a reference on using material2+ng2-material in angular-cli. The source is here: https://github.com/justindujardin/ng2-material/tree/master/modules/site

**Closed by justindujardin** 2016-06-11 19:18 UTC

**Comment by leoX2848** [comment] 2016-10-07 20:55
Since with the new version of angular-cli am not been able to install ng2-material. It shows npm ERR! ng2-material@0.6.1 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng2-material@0.6.1 postinstall script 'typings install'.

why this happens .?

**Comment by lukasz-galka** [comment] 2016-10-14 07:34
@leoX2848 did you try to install typings?
`npm install typings -g`

**Comment by codejith** [comment] 2016-10-21 10:17
The issue had been resolved
