### ISSUE TITLE
Angular 2.0.0-beta.2 Breaks Dialog Component

### ISSUE THREAD

**Issue by rmacteague** [justindujardin/ng2-material#41] opened 2016-02-02 22:51 UTC
Added alert example to home page of the starter package.  

Upgraded ngmaterial to 2.1
angular to beta 2.0.0-beta2
Dialog stops working, if I downgrade to beta1 all is fine.  

EXCEPTION: No provider for e! (HomeCmp -> MdDialog -> e)

**Comment by jaroslavrehorka** [comment] 2016-02-03 22:31
This problem does not exists in beta2 branch, however there is on error which I was not able to fix - when you close modal window by either backdrop or button click you got: **Uncaught Attempt to use a dehydrated detector.** this is caused by function emit called from backdrop.ts line 102

there is discussion on angular repo regarding this error - https://github.com/angular/angular/issues/6786

**Comment by justindujardin** [comment] 2016-02-06 19:45
@jaroslavrehorka thanks for looking into this.  I'll check out beta3 and try to get the project up to date today.

**Comment by jaroslavrehorka** [comment] 2016-02-06 21:36
@justindujardin no problem, I was not able to solve that problem, but maybe it is solved with beta 3, have a look at https://github.com/Q-Free-OpenRoads/ng2-material/tree/beta3 this fork probably has beta3 already included...

**Comment by justindujardin** [comment] 2016-02-08 00:52
I published version 0.2.2 today that supports the latest Beta.3 build.  Please try it out and close this issue if your problems are resolved.

**Closed** 2016-02-20 23:49 UTC
